### ISSUE TITLE
下载后如何配置并运行？

### ISSUE THREAD

**Issue by zxyao145** [simple-gr/ketchup.zero#5]
请添加说明在代码下载到本地后如何配置和运行的，例如服务器IP地址的配置，里面似乎是写死的192.168.3.11。

**Comment by simple-gr** [comment]
ip是自定义的，具体的配置与运行  请参考 ：https://github.com/simple-gr/ketchup/wiki/zero

**Comment by phil-guo** [comment]
> 请添加说明在代码下载到本地后如何配置和运行的，例如服务器IP地址的配置，里面似乎是写死的192.168.3.11。

ip是自定义的，具体的配置与运行 请参考 ：https://github.com/simple-gr/ketchup/wiki/zero

**Comment by zxyao145** [comment]
找到了，建议你在这个项目的 README 里面提下。

**Comment by phil-guo** [comment]
> 找到了，建议你在这个项目的 README 里面提下。

好的。
